AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "KhelAppTable Application Lambda Layer"

Parameters:
  StageName:
    Type: String
  StackNamePrefix:
    Type: String

Resources:
  KhelAppLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./nodejs.zip
      LayerName: !Sub "${StackNamePrefix}-layer-${StageName}"
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - "nodejs14.x"

Outputs:
  KhelAppLayer:
    Description: "Npm Layer for all lambda"
    Value: !Ref KhelAppLayer
    Export:
      Name: !Sub "${AWS::StackName}-KhelAppLayer"