AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "KhelAppTable Application"


Parameters:
  StageName:
    Type: String
  StackNamePrefix:
    Type: String

Resources:
  KhelAppDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackNamePrefix}-khelApp-table-${StageName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: details
          AttributeType: S
        - AttributeName: role
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: details
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Sub ${StackNamePrefix}-basedOnRole-${StageName}
          Projection:
              ProjectionType: ALL
          KeySchema:
            - KeyType: HASH
              AttributeName: role
            - KeyType: RANGE
              AttributeName: id
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"

Outputs:
  KhelAppTable:
    Description: "TT App dynamoDb table"
    Value: !Ref KhelAppDynamoTable
    Export:
      Name: !Sub "${StackNamePrefix}-KhelAppTable"
  KhelAppTableArn:
    Description: "TT App table ARN"
    Value: !GetAtt KhelAppDynamoTable.Arn
  KhelAppTableName:
    Description: "KhelAppTable table name"
    Value: !Sub "${StackNamePrefix}-khelApp-table-${StageName}"
  KhelAppTableIndexName:
    Description: "KhelApp Table GSI Index Name"
    Value: !Sub  "${StackNamePrefix}-basedOnRole-${StageName}"
  KhelAppDynamoStreamARN:
    Description: "KhelAppDynamoStreamARN"
    Value: !GetAtt KhelAppDynamoTable.StreamArn
    Export:
      Name: !Sub "${AWS::StackName}-KhelAppDynamoStreamARN"