AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "TTAppTable Application"


Parameters:
  StageName:
    Type: String
  StackNamePrefix:
    Type: String

Resources:
  TTAppDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${StackNamePrefix}-ttApp-table-${StageName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: details
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: details
          KeyType: RANGE


Outputs:
  TTAppTable:
    Description: "TT App dynamoDb table"
    Value: !Ref TTAppDynamoTable
    Export:
      Name: !Sub "${StackNamePrefix}-TTAppTable"
  TTAppTableArn:
    Description: "TT App table ARN"
    Value: !GetAtt TTAppDynamoTable.Arn
  TTAppTableName:
    Description: "TTAppTable table name"
    Value: !Sub "${StackNamePrefix}-ttApp-table-${StageName}"