AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "KhelAppTable  Application Cloudfront Template"

Parameters:
  StackNamePrefix:
    Type: String

Resources:
  KhelAppOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
          Comment: !Sub This is an Origin Access Identity(OAI) for cloudfront distribution for ${StackNamePrefix}

Outputs:
  KhelAppOriginAccessIdentity:
    Description: "KhelApp origin Access Identity"
    Value: !Ref KhelAppOriginAccessIdentity
  
  S3CanonicalUserId:
    Description: "S3 Canonical User Id"
    Value: !GetAtt KhelAppOriginAccessIdentity.S3CanonicalUserId