AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: KhelAppTable Application
Parameters:
  StageName:
    Default: debug
    Type: String
    AllowedValues:
    - local
    - debug
    - dev
    - prod
  SSLCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /khelApp/Application/SSLCertificateArn
  ApiSSLCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /khelApp/Application/ApiSSLCertificateArn
  GoogleClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /khelApp/Application/GoogleClientId
  GoogleSecretKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /khelApp/Application/GoogleSecretKey
  IsEnableCustomDomain:
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
Mappings:
  URLs:
    debug:
      URL: https://khel.ns-info.xyz/index.html
    dev:
      URL: https://dev-khel.inapp.com/index.html
    prod:
      URL: https://khel.inapp.com/index.html
    local:
      URL: http://localhost:5173/
  DomainName:
    debug:
      URL: khel.ns-info.xyz
    dev:
      URL: dev-khel.inapp.com
    prod:
      URL: khel.inapp.com
    local:
      URL: localhost:5173
  ApiDomainName:
    debug:
      URL: api-khel.ns-info.xyz
    dev:
      URL: api-dev-khel.inapp.com
    prod:
      URL: api-khel.inapp.com
    local:
      URL: api-localhost:5173
  StackNamePrefix:
    debug:
      Name: khelapp-debug-stack
    dev:
      Name: khelapp-dev-stack
    prod:
      Name: khelapp-stack
    local:
      Name: khelapp-local-stack
Resources:
  LambdaLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/74231e963d94f11643d77a3a204b9f28.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: LambdaLayerStack
  DynamoDbTableStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/f79926e4a9253cdcedfa0dd7ec1da8a4.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: DynamoDbTableStack
  AccessIdentiyStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/1849584291dd03bd8fada6df1ca724a4.template
      Parameters:
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    Metadata:
      SamResourceId: AccessIdentiyStack
  FrontendBucketStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/950d529ad0639fec5bb9d0d8f11911f8.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
        IsEnableCustomDomain:
          Ref: IsEnableCustomDomain
        DomainName:
          Fn::Sub:
          - https://${domain}
          - domain:
              Fn::FindInMap:
              - DomainName
              - Ref: StageName
              - URL
        S3CanonicalUserId:
          Fn::GetAtt:
          - AccessIdentiyStack
          - Outputs.S3CanonicalUserId
    Metadata:
      SamResourceId: FrontendBucketStack
  CloudFrontStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/af36ff9848b7a2b092cb76095e7b47b2.template
      Parameters:
        FrontendBucketDomainName:
          Fn::GetAtt:
          - FrontendBucketStack
          - Outputs.FrontendBucketDomainName
        KhelAppOriginAccessIdentity:
          Fn::GetAtt:
          - AccessIdentiyStack
          - Outputs.KhelAppOriginAccessIdentity
        IsEnabledCustomeDomain:
          Ref: IsEnableCustomDomain
        Alias:
          Fn::FindInMap:
          - DomainName
          - Ref: StageName
          - URL
        SSLCertificateArn:
          Ref: SSLCertificateArn
    Metadata:
      SamResourceId: CloudFrontStack
  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/2a4292502416f1cbfb0033faeaf86ea6.template
      Parameters:
        StageName:
          Ref: StageName
        URLs:
          Fn::FindInMap:
          - URLs
          - Ref: StageName
          - URL
        GoogleClientId:
          Ref: GoogleClientId
        GoogleSecretKey:
          Ref: GoogleSecretKey
        KhelAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.KhelAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableName
        KhelAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableArn
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: CognitoStack
  FunctionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/0b60d36f976a7e10f82d66571937ad19.template
      Parameters:
        StageName:
          Ref: StageName
        UserPoolArn:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolArn
        KhelAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.KhelAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableName
        KhelAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableArn
        KhelAppTableIndex:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableIndexName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
        WebSocketUrl:
          Fn::GetAtt:
          - SocketStack
          - Outputs.KhelAppWebSocketGatewayEndpoint
        WebSocketPostUrl:
          Fn::GetAtt:
          - SocketStack
          - Outputs.KhelAppWebSocketGatewayPOSTEndpoint
        KhelAppDynamoStreamARN:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppDynamoStreamARN
        IsEnableCustomDomain:
          Ref: IsEnableCustomDomain
        ApiDomainName:
          Fn::FindInMap:
          - ApiDomainName
          - Ref: StageName
          - URL
        ApiSSLCertificateArn:
          Ref: ApiSSLCertificateArn
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: FunctionStack
  SocketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/khelapp/6ef1bda2c8eeda595d95dc6efab7b9a5.template
      Parameters:
        StageName:
          Ref: StageName
        UserPoolId:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolId
        UserPoolClientId:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolClientId
        KhelAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.KhelAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableName
        KhelAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableArn
        KhelAppTableIndex:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.KhelAppTableIndexName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: SocketStack
Outputs:
  KhelAppApiURL:
    Description: Api Gateway base url
    Value:
      Fn::GetAtt:
      - FunctionStack
      - Outputs.KhelAppApiURL
  UserPoolId:
    Description: User pool ID
    Value:
      Fn::GetAtt:
      - CognitoStack
      - Outputs.UserPoolId
  UserPoolClientId:
    Description: User pool Client ID
    Value:
      Fn::GetAtt:
      - CognitoStack
      - Outputs.UserPoolClientId
  CloudFrontUrl:
    Description: CloudFront Url for frontend
    Value:
      Fn::GetAtt:
      - CloudFrontStack
      - Outputs.CloudFrontUrl
  CloudFrontDistributionId:
    Description: CloudFront Distribution Id
    Value:
      Fn::GetAtt:
      - CloudFrontStack
      - Outputs.CloudFrontDistributionId
