AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TTAppTable Application
Parameters:
  StageName:
    Default: local
    Type: String
    AllowedValues:
    - dev
    - prod
    - local
  GoogleClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/googleClientId
  GoogleSecretKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/googleSecretKey
Mappings:
  DomainName:
    dev:
      URL: https://dev-dice.inapp.com/index.html
    prod:
      URL: https://dice.inapp.com/index.html
    local:
      URL: http://localhost:5173/
  StackNamePrefix:
    dev:
      Name: ttapp-dev-stack
    prod:
      Name: ttapp-stack
    local:
      Name: ttapp-local-stack
Resources:
  LambdaLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/f4de5af9af703224cea1d292d81265dc.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: LambdaLayerStack
  DynamoDbTableStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/5f9d64b12e240d2f2ba0efbbcc99d9af.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: DynamoDbTableStack
  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/e7adfe6f0937da6ca132e73769188652.template
      Parameters:
        StageName:
          Ref: StageName
        URLs:
          Fn::FindInMap:
          - DomainName
          - Ref: StageName
          - URL
        GoogleClientId:
          Ref: GoogleClientId
        GoogleSecretKey:
          Ref: GoogleSecretKey
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: CognitoStack
  FunctionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/87228a0f4124b0dd204a394f143e1350.template
      Parameters:
        StageName:
          Ref: StageName
        UserPoolArn:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolArn
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: FunctionStack
