AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TTAppTable Application
Parameters:
  StageName:
    Default: local
    Type: String
    AllowedValues:
    - dev
    - prod
    - local
  GoogleClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/googleClientId
  GoogleSecretKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/googleSecretKey
Mappings:
  DomainName:
    dev:
      URL: https://dev-dice.inapp.com/index.html
    prod:
      URL: https://dice.inapp.com/index.html
    local:
      URL: http://localhost:5173/
  StackNamePrefix:
    dev:
      Name: ttapp-dev-stack
    prod:
      Name: ttapp-stack
    local:
      Name: ttapp-local-stack
Resources:
  LambdaLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/a4571950ae80630b5f053c694f77ef2e.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: LambdaLayerStack
  DynamoDbTableStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/d0c28ae052876b66caccc155ac2a9a54.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: DynamoDbTableStack
  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/686e5c79942cf9abccace85372c900b5.template
      Parameters:
        StageName:
          Ref: StageName
        URLs:
          Fn::FindInMap:
          - DomainName
          - Ref: StageName
          - URL
        GoogleClientId:
          Ref: GoogleClientId
        GoogleSecretKey:
          Ref: GoogleSecretKey
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: CognitoStack
  FunctionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/008d0a47610b5c51747e302d01387ec4.template
      Parameters:
        StageName:
          Ref: StageName
        UserPoolArn:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolArn
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        TTAppTableIndex:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableIndexName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
        WebSocketUrl:
          Fn::GetAtt:
          - SocketStack
          - Outputs.TTAppWebSocketGatewayEndpoint
        WebSocketPostUrl:
          Fn::GetAtt:
          - SocketStack
          - Outputs.TTAppWebSocketGatewayPOSTEndpoint
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: FunctionStack
  SocketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/ebdbc6625a5b17ba57ed4c0f554685e7.template
      Parameters:
        StageName:
          Ref: StageName
        UserPoolId:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolId
        UserPoolClientId:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolClientId
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        TTAppTableIndex:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableIndexName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: SocketStack
Outputs:
  TTAppApiURL:
    Description: Api Gateway base url
    Value:
      Fn::GetAtt:
      - FunctionStack
      - Outputs.TTAppApiURL
  UserPoolId:
    Description: User pool ID
    Value:
      Fn::GetAtt:
      - CognitoStack
      - Outputs.UserPoolId
  UserPoolClientId:
    Description: User pool Client ID
    Value:
      Fn::GetAtt:
      - CognitoStack
      - Outputs.UserPoolClientId
