AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TTAppTable Application
Parameters:
  StageName:
    Default: local
    Type: String
    AllowedValues:
    - local
    - debug
    - dev
    - prod
  SSLCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/SSLCertificateArn
  ApiSSLCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/ApiSSLCertificateArn
  GoogleClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/GoogleClientId
  GoogleSecretKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ttApp/Application/GoogleSecretKey
  IsEnableCustomDomain:
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
Mappings:
  URLs:
    debug:
      URL: https://khel.ns-info.xyz/index.html
    dev:
      URL: https://dev-khel.inapp.com/index.html
    prod:
      URL: https://khel.inapp.com/index.html
    local:
      URL: http://localhost:5173/
  DomainName:
    debug:
      URL: khel.ns-info.xyz
    dev:
      URL: dev-khel.inapp.com
    prod:
      URL: khel.inapp.com
    local:
      URL: localhost:5173
  ApiDomainName:
    debug:
      URL: api-khel.ns-info.xyz
    dev:
      URL: api-dev-khel.inapp.com
    prod:
      URL: api-khel.inapp.com
    local:
      URL: api-localhost:5173
  StackNamePrefix:
    debug:
      Name: ttapp-debug-stack
    dev:
      Name: ttapp-dev-stack
    prod:
      Name: ttapp-stack
    local:
      Name: ttapp-local-stack
Resources:
  LambdaLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/963b4e5ea625de95fa6215ad92121a76.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: LambdaLayerStack
  DynamoDbTableStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/8067c784799401f1fedcb5e196e3c579.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: DynamoDbTableStack
  AccessIdentiyStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/66de8a12e9c58d1c71d5e6d42e26b092.template
      Parameters:
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    Metadata:
      SamResourceId: AccessIdentiyStack
  FrontendBucketStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/2860e3dc516c63b6187609ff199b6ab7.template
      Parameters:
        StageName:
          Ref: StageName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
        IsEnableCustomDomain:
          Ref: IsEnableCustomDomain
        DomainName:
          Fn::Sub:
          - https://${domain}
          - domain:
              Fn::FindInMap:
              - DomainName
              - Ref: StageName
              - URL
        S3CanonicalUserId:
          Fn::GetAtt:
          - AccessIdentiyStack
          - Outputs.S3CanonicalUserId
    Metadata:
      SamResourceId: FrontendBucketStack
  CloudFrontStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/0558398bc607129d7d6d9efa86d7c853.template
      Parameters:
        FrontendBucketDomainName:
          Fn::GetAtt:
          - FrontendBucketStack
          - Outputs.FrontendBucketDomainName
        TTAppOriginAccessIdentity:
          Fn::GetAtt:
          - AccessIdentiyStack
          - Outputs.TTAppOriginAccessIdentity
        IsEnabledCustomeDomain:
          Ref: IsEnableCustomDomain
        Alias:
          Fn::FindInMap:
          - DomainName
          - Ref: StageName
          - URL
        SSLCertificateArn:
          Ref: SSLCertificateArn
    Metadata:
      SamResourceId: CloudFrontStack
  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/686e5c79942cf9abccace85372c900b5.template
      Parameters:
        StageName:
          Ref: StageName
        URLs:
          Fn::FindInMap:
          - URLs
          - Ref: StageName
          - URL
        GoogleClientId:
          Ref: GoogleClientId
        GoogleSecretKey:
          Ref: GoogleSecretKey
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: CognitoStack
  FunctionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/e2e2d87dc23aa48bf16025e0a8351ef0.template
      Parameters:
        StageName:
          Ref: StageName
        UserPoolArn:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolArn
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        TTAppTableIndex:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableIndexName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
        WebSocketUrl:
          Fn::GetAtt:
          - SocketStack
          - Outputs.TTAppWebSocketGatewayEndpoint
        WebSocketPostUrl:
          Fn::GetAtt:
          - SocketStack
          - Outputs.TTAppWebSocketGatewayPOSTEndpoint
        TTAppDynamoStreamARN:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppDynamoStreamARN
        IsEnableCustomDomain:
          Ref: IsEnableCustomDomain
        ApiDomainName:
          Fn::FindInMap:
          - ApiDomainName
          - Ref: StageName
          - URL
        ApiSSLCertificateArn:
          Ref: ApiSSLCertificateArn
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: FunctionStack
  SocketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.ap-south-1.amazonaws.com/ttapp-dev/ebdbc6625a5b17ba57ed4c0f554685e7.template
      Parameters:
        StageName:
          Ref: StageName
        UserPoolId:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolId
        UserPoolClientId:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolClientId
        TTAppLayer:
          Fn::GetAtt:
          - LambdaLayerStack
          - Outputs.TTAppLayer
        TableName:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableName
        TTAppTableArn:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableArn
        TTAppTableIndex:
          Fn::GetAtt:
          - DynamoDbTableStack
          - Outputs.TTAppTableIndexName
        StackNamePrefix:
          Fn::FindInMap:
          - StackNamePrefix
          - Ref: StageName
          - Name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      SamResourceId: SocketStack
Outputs:
  TTAppApiURL:
    Description: Api Gateway base url
    Value:
      Fn::GetAtt:
      - FunctionStack
      - Outputs.TTAppApiURL
  UserPoolId:
    Description: User pool ID
    Value:
      Fn::GetAtt:
      - CognitoStack
      - Outputs.UserPoolId
  UserPoolClientId:
    Description: User pool Client ID
    Value:
      Fn::GetAtt:
      - CognitoStack
      - Outputs.UserPoolClientId
  CloudFrontUrl:
    Description: CloudFront Url for frontend
    Value:
      Fn::GetAtt:
      - CloudFrontStack
      - Outputs.CloudFrontUrl
  CloudFrontDistributionId:
    Description: CloudFront Distribution Id
    Value:
      Fn::GetAtt:
      - CloudFrontStack
      - Outputs.CloudFrontDistributionId
