AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "KhelAppTable Application"


Parameters:
  StageName: 
    Default: prod
    Type: String
    AllowedValues:
      - local
      - debug
      - dev
      - prod

  StackNamePrefix:
    Type: String
    Default: khel-app

  SSLCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/khelApp/Application/SSLCertificateArn"

  ApiSSLCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/khelApp/Application/ApiSSLCertificateArn"

  GoogleClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/khelApp/Application/GoogleClientId"

  GoogleSecretKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/khelApp/Application/GoogleSecretKey"

  IsEnableCustomDomain:
    Type: String
    Default: "true"
    AllowedValues:
         - "true"
         - "false"

Mappings:
  URLs:
    debug:
      URL: "https://khel.ns-info.xyz/index.html"
    dev:
      URL: https://dev-khel.inapp.com/index.html
    prod:
      URL: https://khel.inapp.com/index.html
    local:
      URL: http://localhost:5173/
  DomainName:
    debug:
      URL: khel.ns-info.xyz
    dev:
      URL: dev-khel.inapp.com
    prod:
      URL: khel.inapp.com
    local:
      URL: localhost:5173
  ApiDomainName:
    debug:
      URL: api-khel.ns-info.xyz
    dev:
      URL: api-dev-khel.inapp.com
    prod:
      URL: api-khel.inapp.com
    local:
      URL: api-localhost:5173

Resources:
  LambdaLayerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambdaLayerStack/template.yaml
      Parameters:
        StageName: !Ref StageName
        StackNamePrefix: !Ref StackNamePrefix
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  
  DynamoDbTableStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamodbStack/template.yaml
      Parameters:
        StageName: !Ref StageName
        StackNamePrefix: !Ref StackNamePrefix
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  
  AccessIdentiyStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: ./infrastructure/access-identity-template.yaml
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix

  FrontendBucketStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: ./infrastructure/frontend-bucket-template.yaml
      Parameters:
        StageName: !Ref StageName
        StackNamePrefix: !Ref StackNamePrefix
        IsEnableCustomDomain: !Ref IsEnableCustomDomain
        DomainName: !Sub
          - https://${domain}
          - domain: !FindInMap [DomainName, !Ref StageName, URL]
        S3CanonicalUserId: !GetAtt AccessIdentiyStack.Outputs.S3CanonicalUserId
  
  CloudFrontStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: ./infrastructure/cloudfront-template.yaml
      Parameters:
        FrontendBucketDomainName: !GetAtt FrontendBucketStack.Outputs.FrontendBucketDomainName
        KhelAppOriginAccessIdentity: !GetAtt AccessIdentiyStack.Outputs.KhelAppOriginAccessIdentity
        IsEnabledCustomeDomain: !Ref IsEnableCustomDomain
        Alias: !FindInMap [DomainName, !Ref StageName, URL ]
        SSLCertificateArn: !Ref SSLCertificateArn

  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognitoStack/template.yaml
      Parameters:
        StageName: !Ref StageName
        URLs: !FindInMap [URLs, !Ref StageName, URL]
        GoogleClientId: !Ref GoogleClientId
        GoogleSecretKey: !Ref GoogleSecretKey
        KhelAppLayer: !GetAtt LambdaLayerStack.Outputs.KhelAppLayer
        TableName: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableName
        KhelAppTableArn: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableArn
        StackNamePrefix: !Ref StackNamePrefix
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  
  FunctionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./functionStack/template.yaml
      Parameters:
        StageName: !Ref StageName
        UserPoolArn: !GetAtt CognitoStack.Outputs.UserPoolArn
        KhelAppLayer: !GetAtt LambdaLayerStack.Outputs.KhelAppLayer
        TableName: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableName
        KhelAppTableArn: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableArn
        KhelAppTableIndex: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableIndexName
        StackNamePrefix: !Ref StackNamePrefix
        WebSocketUrl: !GetAtt SocketStack.Outputs.KhelAppWebSocketGatewayEndpoint
        WebSocketPostUrl: !GetAtt SocketStack.Outputs.KhelAppWebSocketGatewayPOSTEndpoint
        KhelAppDynamoStreamARN: !GetAtt DynamoDbTableStack.Outputs.KhelAppDynamoStreamARN
        IsEnableCustomDomain: !Ref IsEnableCustomDomain
        ApiDomainName: !FindInMap [ApiDomainName, !Ref StageName, URL]
        ApiSSLCertificateArn: !Ref ApiSSLCertificateArn
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  SocketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./socketStack/template.yaml
      Parameters:
        StageName: !Ref StageName
        UserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt CognitoStack.Outputs.UserPoolClientId
        KhelAppLayer: !GetAtt LambdaLayerStack.Outputs.KhelAppLayer
        TableName: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableName
        KhelAppTableArn: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableArn
        KhelAppTableIndex: !GetAtt DynamoDbTableStack.Outputs.KhelAppTableIndexName
        StackNamePrefix: !Ref StackNamePrefix
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

Outputs:
  KhelAppApiURL:
    Description: Api Gateway base url
    Value: !GetAtt FunctionStack.Outputs.KhelAppApiURL
  UserPoolId:
    Description: User pool ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolId
  UserPoolClientId:
    Description: User pool Client ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId
  CloudFrontUrl:
    Description: CloudFront Url for frontend
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontUrl
  CloudFrontDistributionId:
    Description: CloudFront Distribution Id
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDistributionId

